apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
    export-labels: "true"
    le__example: test
spec:
  containers:
  - name: nginx
    image: nginx:test
    imagePullPolicy: IfNotPresent