---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-exporter-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-exporter-clusterrole
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics # access /metrics/resource
  - nodes/proxy
  - nodes/stats
  - pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-exporter-clusterrole-binding
roleRef:
  kind: ClusterRole
  name: label-exporter-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: label-exporter-sa
  namespace: monitoring